image: node:14

pages:
  stage: deploy
  before_script:
    - yarn --frozen-lockfile
  script:
    - ASSET_PREFIX='/gosh-okh-search' yarn run build
    - mv public out_of_the_way
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master
